import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { apiPost } from '@/lib/api';

const BG = '#1C1612';
const CARD = '#252018';
const TEXT_C = '#E8E0D0';
const GOLD = '#F5C842';
const CORAL = '#E07B54';
const SAGE = '#8B9E6E';
const MUTED = 'rgba(232,224,208,0.5)';
const DIM = 'rgba(232,224,208,0.25)';

interface Recipe {
  name: string;
  type: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  cookTime: number;
  difficulty: string;
  ingredients: string;
  ingredientsList: string[];
  recipeSteps: string[];
  reason: string;
  savedAt: string;
}

const FILTERS = ['All', 'Breakfast', 'Lunch', 'Snack', 'Dinner'] as const;

const ICONS: Record<string, { name: string; color: string }> = {
  breakfast: { name: 'sunny-outline', color: GOLD },
  lunch:    { name: 'restaurant-outline', color: SAGE },
  snack:    { name: 'flash-outline', color: GOLD },
  dinner:   { name: 'moon-outline', color: CORAL },
};

export default function RecipeBankScreen() {
  const router = useRouter();
  const [all, setAll] = useState<Recipe[]>([]);
  const [filter, setFilter] = useState<typeof FILTERS[number]>('All');
  const [query, setQuery] = useState('');
  const [openId, setOpenId] = useState<string | null>(null);
  const [generatingId, setGeneratingId] = useState<string | null>(null);
  const flatListRef = useRef<FlatList>(null);

  const load = useCallback(() => {
    AsyncStorage.getItem('jonno_meal_plan_history').then(raw => {
      if (!raw) return;
      const parsed: any[] = JSON.parse(raw);
      // Only keep recipes that have full data (generated by agent)
      const valid = parsed.filter(r => r.name && r.calories > 0);
      // Deduplicate by normalized name, keep most recent
      const seen = new Map<string, Recipe>();
      for (const r of valid) {
        const key = r.name.toLowerCase().replace(/[^a-z0-9 ]/g, '').trim();
        if (!seen.has(key)) {
          seen.set(key, {
            name: r.name,
            type: r.type ?? 'dinner',
            calories: r.calories ?? 0,
            protein: r.protein ?? 0,
            carbs: r.carbs ?? 0,
            fat: r.fat ?? 0,
            cookTime: r.cookTime ?? 0,
            difficulty: r.difficulty ?? '',
            ingredients: r.ingredients ?? '',
            ingredientsList: Array.isArray(r.ingredientsList) ? r.ingredientsList : [],
            recipeSteps: Array.isArray(r.recipeSteps) ? r.recipeSteps : [],
            reason: r.reason ?? '',
            savedAt: r.savedAt ?? '',
          });
        }
      }
      setAll([...seen.values()]);
    }).catch(() => {});
  }, []);

  useFocusEffect(useCallback(() => { load(); }, [load]));

  // Generate full recipe for a card missing details
  const generateRecipe = useCallback(async (recipe: Recipe, idx: number) => {
    const id = `${recipe.name}-${idx}`;
    setGeneratingId(id);
    setOpenId(id);
    try {
      const prompt = `Generate a detailed recipe for: "${recipe.name}" (${recipe.type}).
Target macros: ${recipe.calories} kcal, ${recipe.protein}g protein, ${recipe.carbs}g carbs, ${recipe.fat}g fat.
Cook time should be around ${recipe.cookTime || 20} minutes, difficulty ${recipe.difficulty || 'Easy'}.
Return ONLY valid JSON, no markdown:
{
  "ingredientsList": ["Ingredient 1 (150g)", "Ingredient 2 (100g)"],
  "ingredients": "Ingredient 1 (150g), Ingredient 2 (100g)",
  "recipeSteps": ["Step 1 instruction.", "Step 2 instruction.", "Step 3 instruction.", "Step 4 instruction.", "Step 5 instruction."],
  "reason": "One sentence why this meal is good for the user.",
  "cookTime": 20,
  "difficulty": "Easy"
}`;
      const res = await apiPost<{ response?: string; reply?: string; content?: string }>('/api/agent/chat', { message: prompt });
      const raw = res.response ?? res.reply ?? (res as any).content ?? '';
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error('No JSON');
      const parsed = JSON.parse(jsonMatch[0]);

      // Update recipe in state
      const updated: Recipe = {
        ...recipe,
        ingredientsList: Array.isArray(parsed.ingredientsList) ? parsed.ingredientsList : [],
        ingredients: parsed.ingredients ?? '',
        recipeSteps: Array.isArray(parsed.recipeSteps) ? parsed.recipeSteps : [],
        reason: parsed.reason ?? recipe.reason ?? '',
        cookTime: parsed.cookTime ?? recipe.cookTime,
        difficulty: parsed.difficulty ?? recipe.difficulty,
      };

      setAll(prev => prev.map(r => r.name === recipe.name && r.savedAt === recipe.savedAt ? updated : r));

      // Persist back to AsyncStorage
      const histRaw = await AsyncStorage.getItem('jonno_meal_plan_history');
      if (histRaw) {
        const history: any[] = JSON.parse(histRaw);
        const match = history.find((h: any) => h.name === recipe.name && h.savedAt === recipe.savedAt);
        if (match) {
          match.ingredientsList = updated.ingredientsList;
          match.ingredients = updated.ingredients;
          match.recipeSteps = updated.recipeSteps;
          match.reason = updated.reason;
          match.cookTime = updated.cookTime;
          match.difficulty = updated.difficulty;
          await AsyncStorage.setItem('jonno_meal_plan_history', JSON.stringify(history));
        }
      }
    } catch {
      // Silent fail — card stays without details
    } finally {
      setGeneratingId(null);
    }
  }, []);

  // Filter + search
  const list = all.filter(r => {
    if (filter !== 'All' && r.type.toLowerCase() !== filter.toLowerCase()) return false;
    if (query.trim()) {
      const q = query.trim().toLowerCase();
      return r.name.toLowerCase().includes(q) || (r.ingredients ?? '').toLowerCase().includes(q);
    }
    return true;
  });

  const hasRecipeDetails = (r: Recipe) => (r.ingredientsList.length > 0 || r.recipeSteps.length > 0);

  return (
    <SafeAreaView style={s.safe} edges={['top']}>
      {/* ── Header ── */}
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} activeOpacity={0.7} hitSlop={12}>
          <Ionicons name="chevron-back" size={24} color={TEXT_C} />
        </TouchableOpacity>
        <View style={{ flex: 1, marginLeft: 12 }}>
          <Text style={s.title}>Recipe Bank</Text>
          <Text style={s.subtitle}>Meals generated by Jonno</Text>
        </View>
        <View style={s.countBadge}>
          <Text style={s.countText}>{all.length}</Text>
        </View>
      </View>

      {/* ── Search ── */}
      <View style={s.searchWrap}>
        <Ionicons name="search-outline" size={16} color={DIM} />
        <TextInput
          style={s.searchInput}
          placeholder="Search recipes..."
          placeholderTextColor={DIM}
          value={query}
          onChangeText={setQuery}
          autoCapitalize="none"
          autoCorrect={false}
        />
        {query.length > 0 && (
          <TouchableOpacity onPress={() => setQuery('')} hitSlop={10}>
            <Ionicons name="close-circle" size={16} color={MUTED} />
          </TouchableOpacity>
        )}
      </View>

      {/* ── Filter chips ── */}
      <View style={s.chipRow}>
        {FILTERS.map(f => (
          <TouchableOpacity
            key={f}
            style={[s.chip, filter === f && s.chipActive]}
            onPress={() => setFilter(f)}
            activeOpacity={0.7}
          >
            <Text style={[s.chipText, filter === f && s.chipTextActive]}>{f}</Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* ── List ── */}
      {list.length === 0 ? (
        <View style={s.empty}>
          <View style={s.emptyIcon}>
            <Ionicons name="book-outline" size={36} color={GOLD} />
          </View>
          <Text style={s.emptyTitle}>{all.length === 0 ? 'No recipes yet' : 'No matches'}</Text>
          <Text style={s.emptySub}>
            {all.length === 0
              ? 'Generate a meal with Jonno and the recipe will be saved here automatically'
              : 'Try a different search or filter'}
          </Text>
          {all.length === 0 && (
            <TouchableOpacity style={s.ctaBtn} onPress={() => router.push('/(tabs)/agent' as any)} activeOpacity={0.85}>
              <Ionicons name="sparkles-outline" size={16} color={BG} />
              <Text style={s.ctaBtnText}>Generate a Meal</Text>
            </TouchableOpacity>
          )}
        </View>
      ) : (
        <FlatList
          data={list}
          keyExtractor={(r, i) => `${r.name}-${i}`}
          contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 40 }}
          showsVerticalScrollIndicator={false}
          renderItem={({ item: r, index: idx }) => {
            const ico = ICONS[r.type.toLowerCase()] ?? ICONS.dinner;
            const id = `${r.name}-${idx}`;
            const open = openId === id;
            const hasDetails = hasRecipeDetails(r);

            const isGenerating = generatingId === id;

            return (
              <TouchableOpacity
                style={s.card}
                onPress={() => {
                  if (hasDetails) {
                    setOpenId(open ? null : id);
                  } else if (!isGenerating) {
                    generateRecipe(r, idx);
                  }
                }}
                activeOpacity={0.8}
              >
                {/* Top row: icon + name + chevron */}
                <View style={s.cardTop}>
                  <View style={[s.mealIcon, { backgroundColor: ico.color + '15' }]}>
                    <Ionicons name={ico.name as any} size={16} color={ico.color} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={s.cardName} numberOfLines={open ? 3 : 1}>{r.name}</Text>
                    <View style={s.metaRow}>
                      <Text style={[s.metaTag, { color: ico.color }]}>
                        {r.type.charAt(0).toUpperCase() + r.type.slice(1)}
                      </Text>
                      {r.cookTime > 0 && (
                        <>
                          <Text style={s.metaSep}>·</Text>
                          <Ionicons name="time-outline" size={10} color={DIM} />
                          <Text style={s.metaVal}>{r.cookTime}m</Text>
                        </>
                      )}
                      {r.difficulty ? (
                        <>
                          <Text style={s.metaSep}>·</Text>
                          <Text style={[s.metaVal, { color: r.difficulty === 'Easy' ? SAGE : r.difficulty === 'Medium' ? GOLD : CORAL }]}>{r.difficulty}</Text>
                        </>
                      ) : null}
                    </View>
                  </View>
                  {isGenerating
                    ? <ActivityIndicator size="small" color={GOLD} />
                    : <Ionicons name={open ? 'chevron-up' : hasDetails ? 'chevron-down' : 'sparkles-outline'} size={16} color={hasDetails ? DIM : GOLD} />
                  }
                </View>

                {/* Macro bar */}
                <View style={s.macroBar}>
                  <View style={s.macroItem}>
                    <Text style={s.macroNum}>{r.calories}</Text>
                    <Text style={s.macroLabel}>kcal</Text>
                  </View>
                  <View style={s.macroDivider} />
                  <View style={s.macroItem}>
                    <Text style={[s.macroNum, { color: CORAL }]}>{r.protein}g</Text>
                    <Text style={s.macroLabel}>Protein</Text>
                  </View>
                  <View style={s.macroDivider} />
                  <View style={s.macroItem}>
                    <Text style={[s.macroNum, { color: GOLD }]}>{r.carbs}g</Text>
                    <Text style={s.macroLabel}>Carbs</Text>
                  </View>
                  <View style={s.macroDivider} />
                  <View style={s.macroItem}>
                    <Text style={[s.macroNum, { color: SAGE }]}>{r.fat}g</Text>
                    <Text style={s.macroLabel}>Fat</Text>
                  </View>
                </View>

                {/* AI reason (collapsed preview) */}
                {r.reason && !open ? <Text style={s.reasonPreview} numberOfLines={1}>{r.reason}</Text> : null}

                {/* ── Expanded ── */}
                {open && (
                  <View style={s.expandWrap}>
                    {/* Reason */}
                    {r.reason ? (
                      <View style={s.reasonCard}>
                        <Ionicons name="sparkles-outline" size={13} color={GOLD} />
                        <Text style={s.reasonText}>{r.reason}</Text>
                      </View>
                    ) : null}

                    {/* Ingredients */}
                    {r.ingredientsList.length > 0 && (
                      <View style={s.section}>
                        <Text style={s.sectionLabel}>INGREDIENTS</Text>
                        {r.ingredientsList.map((ing, i) => (
                          <View key={i} style={s.ingRow}>
                            <View style={s.ingBullet} />
                            <Text style={s.ingText}>{ing}</Text>
                          </View>
                        ))}
                      </View>
                    )}

                    {/* Method */}
                    {r.recipeSteps.length > 0 && (
                      <View style={s.section}>
                        <Text style={s.sectionLabel}>METHOD</Text>
                        {r.recipeSteps.map((step, i) => (
                          <View key={i} style={s.stepRow}>
                            <View style={s.stepBadge}>
                              <Text style={s.stepBadgeText}>{i + 1}</Text>
                            </View>
                            <Text style={s.stepText}>{step}</Text>
                          </View>
                        ))}
                      </View>
                    )}

                    {/* Generating state */}
                    {!r.ingredientsList.length && !r.recipeSteps.length && isGenerating && (
                      <View style={{ alignItems: 'center', paddingVertical: 16, gap: 8 }}>
                        <ActivityIndicator color={GOLD} />
                        <Text style={{ fontSize: 13, color: MUTED }}>Generating recipe...</Text>
                      </View>
                    )}
                  </View>
                )}
              </TouchableOpacity>
            );
          }}
        />
      )}
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },

  // Header
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingTop: 12, paddingBottom: 6 },
  title: { fontSize: 20, fontWeight: '800', color: TEXT_C },
  subtitle: { fontSize: 12, color: DIM, marginTop: 1 },
  countBadge: {
    backgroundColor: 'rgba(245,200,66,0.12)', borderRadius: 10,
    paddingHorizontal: 10, paddingVertical: 4,
  },
  countText: { fontSize: 13, fontWeight: '700', color: GOLD },

  // Search
  searchWrap: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    marginHorizontal: 16, marginTop: 10, marginBottom: 8,
    backgroundColor: CARD, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10,
    borderWidth: 1, borderColor: 'rgba(232,224,208,0.06)',
  },
  searchInput: { flex: 1, fontSize: 14, color: TEXT_C },

  // Chips
  chipRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 6, marginBottom: 12 },
  chip: {
    paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16,
    backgroundColor: 'rgba(232,224,208,0.05)', borderWidth: 1, borderColor: 'rgba(232,224,208,0.08)',
  },
  chipActive: { backgroundColor: 'rgba(245,200,66,0.12)', borderColor: GOLD },
  chipText: { fontSize: 12, fontWeight: '600', color: DIM },
  chipTextActive: { color: GOLD },

  // Empty
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 40, gap: 10 },
  emptyIcon: {
    width: 72, height: 72, borderRadius: 22, alignItems: 'center', justifyContent: 'center',
    backgroundColor: 'rgba(245,200,66,0.08)', borderWidth: 1, borderColor: 'rgba(245,200,66,0.15)',
  },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: TEXT_C },
  emptySub: { fontSize: 13, color: MUTED, textAlign: 'center', lineHeight: 20 },
  ctaBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: GOLD, borderRadius: 20, paddingVertical: 13, paddingHorizontal: 24, marginTop: 8,
  },
  ctaBtnText: { color: BG, fontWeight: '700', fontSize: 14 },

  // Card
  card: {
    backgroundColor: CARD, borderRadius: 16, marginBottom: 10,
    borderWidth: 1, borderColor: 'rgba(232,224,208,0.05)', padding: 14, gap: 10,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  mealIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  cardName: { fontSize: 15, fontWeight: '700', color: TEXT_C },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  metaTag: { fontSize: 11, fontWeight: '600' },
  metaSep: { fontSize: 10, color: DIM },
  metaVal: { fontSize: 11, color: MUTED, fontWeight: '500' },

  // Macros
  macroBar: {
    flexDirection: 'row', backgroundColor: 'rgba(232,224,208,0.03)',
    borderRadius: 10, paddingVertical: 8,
  },
  macroItem: { flex: 1, alignItems: 'center' },
  macroNum: { fontSize: 14, fontWeight: '700', color: TEXT_C },
  macroLabel: { fontSize: 9, color: DIM, marginTop: 1 },
  macroDivider: { width: 1, backgroundColor: 'rgba(232,224,208,0.06)', marginVertical: 2 },

  // Reason
  reasonPreview: { fontSize: 12, color: MUTED, fontStyle: 'italic' },
  reasonCard: {
    flexDirection: 'row', gap: 8, alignItems: 'flex-start',
    backgroundColor: 'rgba(245,200,66,0.06)', borderRadius: 10, padding: 10,
  },
  reasonText: { fontSize: 13, color: 'rgba(232,224,208,0.6)', flex: 1, lineHeight: 19, fontStyle: 'italic' },

  // Expanded
  expandWrap: { gap: 12, marginTop: 2 },
  section: { gap: 6 },
  sectionLabel: { fontSize: 10, fontWeight: '700', color: GOLD, letterSpacing: 0.6 },

  ingRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingLeft: 2 },
  ingBullet: { width: 4, height: 4, borderRadius: 2, backgroundColor: DIM, marginTop: 7 },
  ingText: { fontSize: 13, color: TEXT_C, flex: 1, lineHeight: 19 },

  stepRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
  stepBadge: {
    width: 20, height: 20, borderRadius: 10, backgroundColor: 'rgba(245,200,66,0.1)',
    alignItems: 'center', justifyContent: 'center',
  },
  stepBadgeText: { fontSize: 10, fontWeight: '700', color: GOLD },
  stepText: { fontSize: 13, color: TEXT_C, flex: 1, lineHeight: 19 },
});
