import React, { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { usePreferences } from '@/hooks/usePreferences';
import { useMealPlan } from '@/hooks/useMealPlan';
import { getPreferencesSummary } from '@/services/preferencesService';
import PreferencesSheet from '@/components/Agent/PreferencesSheet';
import MealPlanCard from '@/components/Agent/MealPlanCard';
import RecipeSheet from '@/components/Agent/RecipeSheet';
import GeneratingLoader from '@/components/Agent/GeneratingLoader';
import type { Meal } from '@/types/mealPlan';

// ── Nutrition targets (from user profile — wired to real profile later) ────────

const NUTRITION_TARGETS = {
  calories: 2984,
  protein:  191,
  carbs:    250,
  fat:      70,
  goal:     'Build Muscle',
};

// ── Screen ────────────────────────────────────────────────────────────────────

export default function AgentScreen() {
  const {
    preferences,
    hasAnyPreferences,
    completeOnboarding,
  } = usePreferences();

  const {
    state,
    planType,
    days,
    selectedDayIndex,
    isRegenerating,
    error,
    generate,
    regenerate,
    markMealLogged,
    getAllIngredients,
    sendToCart,
    resetPlan,
    setSelectedDayIndex,
  } = useMealPlan();

  const [showPreferences, setShowPreferences] = useState(false);
  const [selectedMeal,    setSelectedMeal]    = useState<Meal | null>(null);
  const [showRecipe,      setShowRecipe]      = useState(false);

  const preferencesTags = getPreferencesSummary(preferences);
  const selectedDay     = days[selectedDayIndex];

  const handleGenerate = useCallback((type: 'today' | 'week') => {
    generate(type, preferences, NUTRITION_TARGETS);
  }, [preferences, generate]);

  const handleSendToCart = useCallback(() => {
    sendToCart();
    // TODO: populate smart cart with getAllIngredients() when smart cart service accepts ingredient lists
  }, [sendToCart]);

  const handleOpenRecipe = useCallback((meal: Meal) => {
    setSelectedMeal(meal);
    setShowRecipe(true);
  }, []);

  // ── GENERATING ───────────────────────────────────────────────────────────────

  if (state === 'generating') {
    return (
      <GeneratingLoader type={planType} preferences={preferences} />
    );
  }

  // ── PLAN READY ───────────────────────────────────────────────────────────────

  if (state === 'plan_ready' && selectedDay) {
    const ingredientCount = getAllIngredients().length;

    return (
      <SafeAreaView style={s.safe} edges={['top']}>
        <ScrollView
          contentContainerStyle={s.scroll}
          showsVerticalScrollIndicator={false}
        >
          {/* Header */}
          <View style={s.header}>
            <View>
              <Text style={s.title}>
                {planType === 'today' ? "Today's Plan" : 'This Week'}
              </Text>
              <Text style={s.subtitle}>Generated by Jonno ✦</Text>
            </View>
            <View style={s.headerActions}>
              <TouchableOpacity
                style={s.regenBtn}
                onPress={() => regenerate(preferences, NUTRITION_TARGETS)}
                disabled={isRegenerating}
                activeOpacity={0.8}
              >
                {isRegenerating
                  ? <ActivityIndicator size="small" color="#2DD4BF" />
                  : <Text style={s.regenBtnText}>↻ Regenerate</Text>}
              </TouchableOpacity>
              <TouchableOpacity onPress={resetPlan} style={s.closeBtn} activeOpacity={0.75}>
                <Ionicons name="close" size={18} color="#94A3B8" />
              </TouchableOpacity>
            </View>
          </View>

          {/* Day selector — week mode only */}
          {planType === 'week' && (
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={s.daySelectorContent}
              style={s.daySelector}
            >
              {days.map((day, i) => (
                <TouchableOpacity
                  key={i}
                  style={[s.dayPill, i === selectedDayIndex && s.dayPillActive]}
                  onPress={() => setSelectedDayIndex(i)}
                  activeOpacity={0.8}
                >
                  <Text style={[s.dayPillText, i === selectedDayIndex && s.dayPillTextActive]}>
                    {day.dayLabel.substring(0, 3)}
                  </Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          )}

          {/* Meal cards */}
          {(['breakfast', 'lunch', 'snack', 'dinner'] as const).map(mealType => {
            const meal = selectedDay.meals[mealType];
            if (!meal) return null;
            return (
              <MealPlanCard
                key={mealType}
                meal={meal}
                onLog={() => markMealLogged(selectedDayIndex, mealType)}
                onRecipe={() => handleOpenRecipe(meal)}
              />
            );
          })}

          {/* Daily totals */}
          <View style={s.totalsCard}>
            <Text style={s.totalsHeading}>
              {planType === 'today' ? "Today's totals" : `${selectedDay.dayLabel}`}
            </Text>
            <View style={s.totalsRow}>
              {[
                { label: 'Cal',     value: String(selectedDay.totalCalories),    color: '#1E293B' },
                { label: 'Protein', value: `${selectedDay.totalProtein}g`,        color: '#16A34A' },
                { label: 'Carbs',   value: `${selectedDay.totalCarbs}g`,          color: '#D97706' },
                { label: 'Fat',     value: `${selectedDay.totalFat}g`,            color: '#7C3AED' },
              ].map(stat => (
                <View key={stat.label} style={s.totalStat}>
                  <Text style={[s.totalValue, { color: stat.color }]}>{stat.value}</Text>
                  <Text style={s.totalLabel}>{stat.label}</Text>
                </View>
              ))}
            </View>
          </View>

          {/* Send to cart CTA */}
          <TouchableOpacity
            style={s.cartBtn}
            onPress={handleSendToCart}
            activeOpacity={0.85}
          >
            <LinearGradient
              colors={['#2DD4BF', '#0EA5E9']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={s.cartBtnGradient}
            >
              <View style={s.cartIconCircle}>
                <Text style={{ fontSize: 26 }}>🛒</Text>
              </View>
              <View style={{ flex: 1 }}>
                <Text style={s.cartBtnTitle}>Send to Smart Cart</Text>
                <Text style={s.cartBtnSub}>
                  {ingredientCount} ingredients · Woolworths or Coles
                </Text>
              </View>
              <View style={s.cartArrow}>
                <Ionicons name="arrow-forward" size={18} color="white" />
              </View>
            </LinearGradient>
          </TouchableOpacity>

          <View style={{ height: 32 }} />
        </ScrollView>

        <RecipeSheet
          meal={selectedMeal}
          visible={showRecipe}
          onClose={() => setShowRecipe(false)}
        />
      </SafeAreaView>
    );
  }

  // ── CART SENT ────────────────────────────────────────────────────────────────

  if (state === 'cart_sent') {
    return (
      <SafeAreaView style={s.safe} edges={['top']}>
        <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
          <View style={s.header}>
            <Text style={s.title}>Jonno</Text>
          </View>

          <View style={s.successCard}>
            <Text style={s.successEmoji}>✅</Text>
            <Text style={s.successTitle}>Cart is ready!</Text>
            <Text style={s.successSub}>
              Ingredients sent to your Smart Cart.{'\n'}Order from Woolworths or Coles.
            </Text>
            <TouchableOpacity
              style={s.openCartBtn}
              onPress={() => router.push('/(tabs)/cart' as any)}
              activeOpacity={0.85}
            >
              <Text style={s.openCartBtnText}>Open Smart Cart →</Text>
            </TouchableOpacity>
          </View>

          {/* Recipes */}
          <Text style={s.recipesHeader}>Recipes for your meals</Text>

          {days[0] &&
            (['breakfast', 'lunch', 'snack', 'dinner'] as const).map(mealType => {
              const meal = days[0].meals[mealType];
              if (!meal) return null;
              return (
                <TouchableOpacity
                  key={mealType}
                  style={s.recipeCard}
                  onPress={() => {
                    setSelectedMeal(meal);
                    setShowRecipe(true);
                  }}
                  activeOpacity={0.8}
                >
                  <Text style={s.recipeEmoji}>{meal.emoji}</Text>
                  <View style={{ flex: 1 }}>
                    <Text style={s.recipeName}>{meal.name}</Text>
                    <Text style={s.recipeMeta}>⏱ {meal.cookTime} min · {meal.difficulty}</Text>
                  </View>
                  <Text style={s.recipeArrow}>Recipe →</Text>
                </TouchableOpacity>
              );
            })}

          <TouchableOpacity style={s.newPlanBtn} onPress={resetPlan} activeOpacity={0.8}>
            <Text style={s.newPlanText}>↺  Plan new meals</Text>
          </TouchableOpacity>

          <View style={{ height: 32 }} />
        </ScrollView>

        <RecipeSheet
          meal={selectedMeal}
          visible={showRecipe}
          onClose={() => setShowRecipe(false)}
        />
      </SafeAreaView>
    );
  }

  // ── IDLE ─────────────────────────────────────────────────────────────────────

  return (
    <SafeAreaView style={s.safe} edges={['top']}>
      <ScrollView
        contentContainerStyle={s.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={s.header}>
          <View>
            <Text style={s.title}>Jonno</Text>
            <View style={s.statusRow}>
              <View style={s.statusDot} />
              <Text style={s.statusText}>AI Meal Planner</Text>
            </View>
          </View>
          <TouchableOpacity
            style={[s.filterBtn, hasAnyPreferences && s.filterBtnActive]}
            onPress={() => setShowPreferences(true)}
            activeOpacity={0.8}
          >
            <Ionicons
              name="options-outline"
              size={20}
              color={hasAnyPreferences ? '#2DD4BF' : '#64748B'}
            />
            {hasAnyPreferences && <View style={s.filterDot} />}
          </TouchableOpacity>
        </View>

        {/* Hero card */}
        <View style={s.heroCard}>
          {/* Icon */}
          <LinearGradient
            colors={['#2DD4BF', '#0EA5E9']}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
            style={s.heroIcon}
          >
            <Text style={s.heroIconText}>✦</Text>
          </LinearGradient>

          <Text style={s.heroTitle}>What are we{'\n'}eating?</Text>
          <Text style={s.heroSubtitle}>
            Jonno builds your meal plan based on your goals and preferences,
            then sends the ingredients straight to your cart.
          </Text>

          <View style={s.heroDivider} />

          {/* Active preferences summary */}
          {hasAnyPreferences && preferencesTags.length > 0 && (
            <ScrollView
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={s.prefTagsRow}
              style={{ marginBottom: 16, width: '100%' }}
            >
              {preferencesTags.map((tag, i) => (
                <View key={i} style={s.prefTag}>
                  <Text style={s.prefTagText}>{tag}</Text>
                </View>
              ))}
              <TouchableOpacity
                onPress={() => setShowPreferences(true)}
                style={{ paddingHorizontal: 8, justifyContent: 'center' }}
              >
                <Text style={{ fontSize: 12, color: '#94A3B8' }}>Edit ✏️</Text>
              </TouchableOpacity>
            </ScrollView>
          )}

          {/* Error state */}
          {error && (
            <View style={s.errorBox}>
              <Text style={s.errorText}>{error}</Text>
            </View>
          )}

          {/* Plan Today */}
          <TouchableOpacity
            style={s.primaryBtn}
            onPress={() => handleGenerate('today')}
            activeOpacity={0.85}
          >
            <View style={s.btnIcon}>
              <Text style={{ fontSize: 22 }}>🍽️</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={s.primaryBtnTitle}>Plan Today's Meals</Text>
              <Text style={s.primaryBtnSub}>Breakfast, lunch, dinner + snack</Text>
            </View>
            <Ionicons name="arrow-forward" size={20} color="white" />
          </TouchableOpacity>

          {/* Plan Week */}
          <TouchableOpacity
            style={s.secondaryBtn}
            onPress={() => handleGenerate('week')}
            activeOpacity={0.85}
          >
            <View style={s.btnIconOutline}>
              <Text style={{ fontSize: 22 }}>📅</Text>
            </View>
            <View style={{ flex: 1 }}>
              <Text style={s.secondaryBtnTitle}>Plan This Week</Text>
              <Text style={s.secondaryBtnSub}>7 days tailored to your goals</Text>
            </View>
            <Ionicons name="arrow-forward" size={20} color="#2DD4BF" />
          </TouchableOpacity>

          {/* Personalise prompt */}
          {!hasAnyPreferences && (
            <TouchableOpacity
              onPress={() => setShowPreferences(true)}
              style={s.personaliseRow}
              activeOpacity={0.75}
            >
              <Text style={s.personaliseText}>
                🎯 Personalise for halal, vegetarian, budget + more →
              </Text>
            </TouchableOpacity>
          )}

          {/* Targets label */}
          <Text style={s.targetsText}>
            Based on: {NUTRITION_TARGETS.goal} · {NUTRITION_TARGETS.calories} cal · {NUTRITION_TARGETS.protein}g protein
          </Text>
        </View>

        {/* How it works */}
        <View style={s.howCard}>
          <Text style={s.howTitle}>How Jonno works</Text>
          {[
            { n: '1', text: 'Jonno generates a personalised meal plan based on your goals' },
            { n: '2', text: 'You review the meals and send ingredients to your Smart Cart' },
            { n: '3', text: 'Order from Woolworths or Coles in a few taps' },
            { n: '4', text: 'Jonno gives you the step-by-step recipe to cook it' },
          ].map(step => (
            <View key={step.n} style={s.howStep}>
              <View style={s.howNum}>
                <Text style={s.howNumText}>{step.n}</Text>
              </View>
              <Text style={s.howText}>{step.text}</Text>
            </View>
          ))}
        </View>

        <View style={{ height: 32 }} />
      </ScrollView>

      <PreferencesSheet
        visible={showPreferences}
        onClose={() => {
          setShowPreferences(false);
          completeOnboarding();
        }}
      />
    </SafeAreaView>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const TEAL = '#2DD4BF';

const s = StyleSheet.create({
  safe:   { flex: 1, backgroundColor: '#EEF4FA' },
  scroll: { paddingBottom: 100 },

  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  title:    { fontSize: 28, fontWeight: '800', color: '#1E293B' },
  subtitle: { fontSize: 12, color: '#64748B', marginTop: 2 },
  statusRow:{ flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 3 },
  statusDot:{ width: 6, height: 6, borderRadius: 3, backgroundColor: '#22C55E' },
  statusText:{ fontSize: 12, color: '#64748B' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },

  filterBtn: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1, borderColor: '#E2E8F0',
    alignItems: 'center', justifyContent: 'center',
  },
  filterBtnActive: { borderColor: 'rgba(45,212,191,0.4)', backgroundColor: 'rgba(45,212,191,0.06)' },
  filterDot: { position: 'absolute', top: 6, right: 6, width: 8, height: 8, borderRadius: 4, backgroundColor: TEAL },

  regenBtn: {
    paddingHorizontal: 14, paddingVertical: 7, borderRadius: 16,
    backgroundColor: 'rgba(45,212,191,0.12)', borderWidth: 1, borderColor: 'rgba(45,212,191,0.3)',
    minWidth: 100, alignItems: 'center',
  },
  regenBtnText: { fontSize: 13, fontWeight: '600', color: TEAL },
  closeBtn:     { width: 34, height: 34, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.8)', borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center' },

  // Day selector
  daySelector: { marginBottom: 6 },
  daySelectorContent: { paddingHorizontal: 16, gap: 8 },
  dayPill:      { paddingHorizontal: 18, paddingVertical: 9, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.75)', borderWidth: 1, borderColor: '#E2E8F0' },
  dayPillActive:{ backgroundColor: TEAL, borderColor: TEAL },
  dayPillText:  { fontSize: 13, fontWeight: '600', color: '#64748B' },
  dayPillTextActive: { color: 'white' },

  // Totals
  totalsCard: {
    marginHorizontal: 16, marginTop: 4, marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.88)', borderRadius: 20, borderWidth: 1,
    borderColor: 'rgba(226,232,240,0.9)', padding: 16,
    shadowColor: '#B0C4D8', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.1, shadowRadius: 10, elevation: 3,
  },
  totalsHeading: { fontSize: 12, fontWeight: '600', color: '#94A3B8', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 10 },
  totalsRow:     { flexDirection: 'row', justifyContent: 'space-around' },
  totalStat:     { alignItems: 'center' },
  totalValue:    { fontSize: 20, fontWeight: '800' },
  totalLabel:    { fontSize: 11, color: '#94A3B8', marginTop: 2 },

  // Cart CTA
  cartBtn:         { marginHorizontal: 16, borderRadius: 26, overflow: 'hidden', shadowColor: TEAL, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 16, elevation: 8 },
  cartBtnGradient: { flexDirection: 'row', alignItems: 'center', paddingVertical: 20, paddingHorizontal: 20, gap: 14 },
  cartIconCircle:  { width: 52, height: 52, borderRadius: 26, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  cartBtnTitle:    { fontSize: 18, fontWeight: '800', color: 'white' },
  cartBtnSub:      { fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
  cartArrow:       { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },

  // Success / Cart Sent
  successCard: {
    marginHorizontal: 16, marginTop: 8,
    backgroundColor: 'rgba(255,255,255,0.88)', borderRadius: 28, borderWidth: 1, borderColor: 'rgba(45,212,191,0.2)',
    padding: 28, alignItems: 'center', gap: 8,
    shadowColor: TEAL, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 14, elevation: 4,
  },
  successEmoji:   { fontSize: 48 },
  successTitle:   { fontSize: 24, fontWeight: '800', color: '#1E293B' },
  successSub:     { fontSize: 15, color: '#64748B', textAlign: 'center', lineHeight: 22 },
  openCartBtn:    { marginTop: 10, backgroundColor: TEAL, borderRadius: 20, paddingHorizontal: 28, paddingVertical: 14 },
  openCartBtnText:{ fontSize: 16, fontWeight: '700', color: 'white' },

  recipesHeader: { fontSize: 18, fontWeight: '800', color: '#1E293B', paddingHorizontal: 20, marginTop: 24, marginBottom: 10 },
  recipeCard:    { marginHorizontal: 16, marginBottom: 10, backgroundColor: 'rgba(255,255,255,0.88)', borderRadius: 20, borderWidth: 1, borderColor: '#E2E8F0', padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 },
  recipeEmoji:   { fontSize: 28 },
  recipeName:    { fontSize: 15, fontWeight: '700', color: '#1E293B' },
  recipeMeta:    { fontSize: 12, color: '#94A3B8', marginTop: 2 },
  recipeArrow:   { fontSize: 13, fontWeight: '600', color: TEAL },

  newPlanBtn:    { marginHorizontal: 16, marginTop: 20, paddingVertical: 14, borderRadius: 18, borderWidth: 1.5, borderColor: '#E2E8F0', backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center' },
  newPlanText:   { fontSize: 15, fontWeight: '600', color: '#64748B' },

  // Hero card (idle)
  heroCard: {
    marginHorizontal: 16, marginTop: 8,
    backgroundColor: 'rgba(255,255,255,0.88)', borderRadius: 28, borderWidth: 1, borderColor: 'rgba(255,255,255,0.95)',
    shadowColor: '#B0C4D8', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.15, shadowRadius: 16, elevation: 8,
    padding: 24, alignItems: 'center',
  },
  heroIcon:     { width: 68, height: 68, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 16, shadowColor: TEAL, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 6 },
  heroIconText: { fontSize: 32, color: 'white' },
  heroTitle:    { fontSize: 30, fontWeight: '800', color: '#1E293B', textAlign: 'center', lineHeight: 36 },
  heroSubtitle: { fontSize: 14, color: '#64748B', textAlign: 'center', lineHeight: 22, marginTop: 10, marginHorizontal: 8 },
  heroDivider:  { width: '100%', height: 1, backgroundColor: '#F1F5F9', marginVertical: 20 },

  prefTagsRow:   { gap: 6, paddingVertical: 2 },
  prefTag:       { backgroundColor: 'rgba(45,212,191,0.1)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(45,212,191,0.25)', paddingHorizontal: 10, paddingVertical: 4 },
  prefTagText:   { fontSize: 12, color: TEAL, fontWeight: '500' },

  errorBox:  { backgroundColor: 'rgba(239,68,68,0.1)', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10, width: '100%', marginBottom: 12 },
  errorText: { fontSize: 13, color: '#DC2626', textAlign: 'center' },

  primaryBtn: {
    width: '100%', backgroundColor: TEAL, borderRadius: 22,
    paddingVertical: 16, paddingHorizontal: 16,
    flexDirection: 'row', alignItems: 'center', gap: 12,
    shadowColor: TEAL, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 8,
  },
  btnIcon:       { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  primaryBtnTitle: { fontSize: 16, fontWeight: '700', color: 'white' },
  primaryBtnSub:   { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 2 },

  secondaryBtn: {
    width: '100%', backgroundColor: 'rgba(255,255,255,0.9)', borderRadius: 22,
    paddingVertical: 16, paddingHorizontal: 16,
    flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 10,
    borderWidth: 1.5, borderColor: 'rgba(45,212,191,0.3)',
  },
  btnIconOutline:    { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(45,212,191,0.1)', alignItems: 'center', justifyContent: 'center' },
  secondaryBtnTitle: { fontSize: 16, fontWeight: '700', color: '#1E293B' },
  secondaryBtnSub:   { fontSize: 12, color: '#94A3B8', marginTop: 2 },

  personaliseRow:  { marginTop: 16, paddingVertical: 8 },
  personaliseText: { fontSize: 13, color: TEAL, textAlign: 'center' },
  targetsText:     { fontSize: 11, color: '#94A3B8', textAlign: 'center', marginTop: 12 },

  // How it works
  howCard: {
    marginHorizontal: 16, marginTop: 14,
    backgroundColor: 'rgba(255,255,255,0.7)', borderRadius: 24, borderWidth: 1, borderColor: 'rgba(226,232,240,0.8)',
    padding: 20, gap: 14,
    shadowColor: '#B0C4D8', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 2,
  },
  howTitle: { fontSize: 15, fontWeight: '700', color: '#1E293B', marginBottom: 2 },
  howStep:  { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  howNum:   { width: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(45,212,191,0.15)', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 },
  howNumText: { fontSize: 12, fontWeight: '800', color: TEAL },
  howText:  { flex: 1, fontSize: 14, color: '#64748B', lineHeight: 20 },
});
