import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppHeader } from "@/components/ui/AppHeader";

const BG    = "#0D0A07";
const WHITE = "#1C1410";
const TEAL  = "#F5C842";
const BORDER= "rgba(255,220,150,0.12)";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={s.section}>
      <Text style={s.sectionTitle}>{title}</Text>
      <View style={s.card}>{children}</View>
    </View>
  );
}
function Para({ children }: { children: React.ReactNode }) {
  return <Text style={s.para}>{children}</Text>;
}
function Bullet({ children }: { children: string }) {
  return (
    <View style={s.bulletRow}>
      <Text style={s.bulletDot}>•</Text>
      <Text style={s.bulletText}>{children}</Text>
    </View>
  );
}

export default function TermsScreen() {
  return (
    <SafeAreaView style={s.safe} edges={["top"]}>
      <AppHeader title="Terms & Conditions" showBack />
      <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
        <View style={s.hero}>
          <Text style={s.heroEmoji}>📋</Text>
          <Text style={s.heroTitle}>Terms & Conditions</Text>
          <Text style={s.heroSub}>Last updated: March 2026 · MacroClaw / Jonno AI</Text>
        </View>

        <Section title="1. Acceptance of Terms">
          <Para>
            By downloading, installing, or using the MacroClaw (Jonno AI) application ("App"), you agree to be
            bound by these Terms & Conditions. If you do not agree, please do not use the App.
          </Para>
        </Section>

        <Section title="2. Description of Service">
          <Para>MacroClaw is an AI-powered nutrition and fitness coaching app that provides:</Para>
          <Bullet>Personalised meal planning and macro tracking</Bullet>
          <Bullet>AI nutrition coaching via the Jonno agent</Bullet>
          <Bullet>Activity tracking and Strava integration</Bullet>
          <Bullet>Smart Cart grocery and meal ordering</Bullet>
          <Bullet>Community features for sharing meals and progress</Bullet>
        </Section>

        <Section title="3. User Accounts">
          <Para>
            You must create an account to use the App. You are responsible for maintaining the confidentiality of
            your credentials and for all activity that occurs under your account. You must be at least 16 years of
            age to create an account.
          </Para>
          <Para>
            You agree to provide accurate, current, and complete information during registration and to keep this
            information updated.
          </Para>
        </Section>

        <Section title="4. Health & Nutrition Disclaimer">
          <Para>
            MacroClaw is for informational and educational purposes only. The App does not provide medical advice,
            diagnosis, or treatment. Content generated by our AI — including meal plans, calorie targets, and
            nutrition guidance — is not a substitute for professional medical or dietary advice.
          </Para>
          <Para>
            Always consult a qualified healthcare provider before making significant changes to your diet or
            exercise programme, especially if you have any medical conditions, allergies, or are pregnant.
          </Para>
        </Section>

        <Section title="5. AI-Generated Content">
          <Para>
            Our App uses large language model technology (Anthropic Claude) to generate personalised
            recommendations. While we strive for accuracy:
          </Para>
          <Bullet>AI responses may occasionally be inaccurate or incomplete</Bullet>
          <Bullet>Calorie and macro data is estimated, not guaranteed</Bullet>
          <Bullet>You should verify any specific dietary advice with a professional</Bullet>
          <Bullet>We do not warrant the fitness of AI output for any medical purpose</Bullet>
        </Section>

        <Section title="6. User Content & Community">
          <Para>
            By posting content (meal photos, comments, progress updates) to the community feed, you grant
            MacroClaw a non-exclusive, royalty-free licence to display that content within the App. You retain
            ownership of your content.
          </Para>
          <Para>You agree not to post content that is:</Para>
          <Bullet>Harmful, offensive, or misleading</Bullet>
          <Bullet>In violation of any third-party intellectual property rights</Bullet>
          <Bullet>Spam, advertising, or unsolicited promotions</Bullet>
        </Section>

        <Section title="7. Third-Party Services">
          <Para>The App integrates with third-party services including:</Para>
          <Bullet>Strava — activity and exercise data</Bullet>
          <Bullet>Uber Eats — meal ordering and delivery</Bullet>
          <Bullet>Anthropic — AI language model for coaching</Bullet>
          <Bullet>Supabase — secure data storage and authentication</Bullet>
          <Para>
            Your use of these integrations is subject to the respective third-party terms of service and privacy
            policies. We are not responsible for the actions of third-party providers.
          </Para>
        </Section>

        <Section title="8. Subscription & Payments">
          <Para>
            MacroClaw offers both a free tier and a premium subscription ("MacroClaw Pro"). Subscription fees are
            billed through the Apple App Store or Google Play. All payments are processed by Apple or Google and
            are subject to their respective terms.
          </Para>
          <Para>
            Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current billing
            period. Refunds are handled in accordance with App Store / Play Store policies.
          </Para>
        </Section>

        <Section title="9. Intellectual Property">
          <Para>
            All content, trademarks, logos, and software in the App are owned by MacroClaw Ltd or its licensors.
            You may not copy, modify, distribute, or reverse-engineer any part of the App without prior written
            consent.
          </Para>
        </Section>

        <Section title="10. Limitation of Liability">
          <Para>
            To the maximum extent permitted by applicable law, MacroClaw and its affiliates shall not be liable
            for any indirect, incidental, special, or consequential damages arising from your use of the App,
            including but not limited to loss of data, personal injury, or health outcomes.
          </Para>
        </Section>

        <Section title="11. Changes to Terms">
          <Para>
            We may update these Terms from time to time. We will notify you of material changes via the App or
            email. Continued use of the App after changes constitutes your acceptance of the updated Terms.
          </Para>
        </Section>

        <Section title="12. Governing Law">
          <Para>
            These Terms are governed by and construed in accordance with the laws of England and Wales. Any
            disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
          </Para>
        </Section>

        <Section title="13. Contact">
          <Para>
            If you have any questions about these Terms, please contact us at:
          </Para>
          <Para>📧  legal@jonnoai.com</Para>
          <Para>🌐  jonnoai.com/terms</Para>
        </Section>

        <View style={s.footer}>
          <Text style={s.footerText}>MacroClaw Ltd · All rights reserved · 2026</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  safe:    { flex: 1, backgroundColor: BG },
  content: { padding: 20, gap: 0, paddingBottom: 60 },

  hero: {
    alignItems: "center", paddingVertical: 24, gap: 6,
    backgroundColor: WHITE, borderRadius: 20, borderWidth: 1, borderColor: BORDER,
    marginBottom: 20,
  },
  heroEmoji: { fontSize: 36 },
  heroTitle: { fontSize: 22, fontWeight: "900", color: "#E8E0D0", letterSpacing: -0.4 },
  heroSub:   { fontSize: 12, color: "rgba(232,224,208,0.4)", fontWeight: "500" },

  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 13, fontWeight: "800", color: TEAL,
    textTransform: "uppercase", letterSpacing: 0.5,
    marginBottom: 6, paddingLeft: 4,
  },
  card: {
    backgroundColor: WHITE, borderRadius: 16, borderWidth: 1, borderColor: BORDER,
    padding: 16, gap: 10,
  },
  para: { fontSize: 14, color: "rgba(232,224,208,0.7)", lineHeight: 22, fontWeight: "400" },
  bulletRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  bulletDot:  { fontSize: 14, color: TEAL, fontWeight: "800", lineHeight: 22 },
  bulletText: { fontSize: 14, color: "rgba(232,224,208,0.7)", lineHeight: 22, flex: 1 },

  footer: { alignItems: "center", paddingTop: 8 },
  footerText: { fontSize: 11, color: "rgba(232,224,208,0.25)" },
});
